# Generated by Django 5.0.7 on 2024-07-21 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'agency',
            },
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ethnicity',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'profession',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=16)),
                ('md5', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.agency')),
                ('ethnicity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.ethnicity')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.gender')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.profession')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
